[package]
name = "day_10"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "0.30.8"
helpers = { path = "../helpers"}
itertools = "0.14.0"
nom = "8.0.0"
nom_locate = "5.0.0"
rstest = "0.26.1"
serde = { version = "1.0.228", features=["derive"]}
serde_json = "1.0.145"
